[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Koopaling Guide"
authors = [{name = "PotatoCouch", email = "potatocouch589@hotmail.com"}]
dynamic = ["version", "description"]
